### ISSUE TITLE
Password cannot be read from terminal

### ISSUE THREAD

**Issue by nbartos** [bh/python-keepass-httpd#1]
It appears that the password cannot be read from a terminal (or even stdin).  This is very insecure since the master password is available in the process list to other users on the same system, and also left in the shell's command history.

It would be really awesome if a prompt for the master password was presented on the terminal if one was not provided on the command line.

**Comment by bh** [comment]
You are right, I'll fix it! 
I think an user prompt to get the password will fix this issue.

**Comment by bh** [comment]
Commit 09c7943 should fix this issue. If so, please close.
