### ISSUE TITLE
"Enter name for new connection" dialogue is shown too small by default

### ISSUE THREAD

**Issue by phpwutz** [bh/python-keepass-httpd#25]
By default, the "Enter name for new connection" dialogue looks like this (tested on MacOS):
![The default display of the enter name dialogue](https://cloud.githubusercontent.com/assets/133333/2844493/2b8b2d1c-d08b-11e3-94d5-7c9fc88eb126.png)

although it is possible to increase the window size to display the "ok" and "cancel" buttons, it would be nicer if the default window size would fit the content.

**Comment by bh** [comment]
This should implicitly fixed with #30
